## 내코드

In [5]:
import numpy as np

In [ ]:
def solution(rows,columns,queries):
    answer = []
    return answer

In [46]:
rows = 6
columns = 6
number_list = []
number2_list= []
querie = [2,2,5,4]
arr= np.arange(1,rows*columns +1)
arr.shape=(rows,columns)
print(arr)
print(arr[2,2])
print(querie[0],querie[0+2])
print(querie[2]-querie[0]-1)
print(querie[0],querie[2]-1)
print("\t")
for i in range(querie[0]-1,querie[2]):
    for j in range(querie[1]-1,querie[3]):
        number=arr[i][j]
        number_list.append(number)

    for i in range(querie[0],querie[2]-1):
        for j in range(querie[1],querie[3]-1):
            number2 = arr[i][j]
        number2_list.append(number2)

print(number_list)
print(number2_list)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
15
2 5
2
2 4
	
[8, 9, 10, 14, 15, 16, 20, 21, 22, 26, 27, 28]
[15, 21, 15, 21, 15, 21, 15, 21]


In [ ]:
rows = 6
columns = 6
queries = [[2,2,5,4],[3,3,6,6],[5,1,6,3]]
solution(rows, columns, queries)

In [ ]:
rows = 3
columns = 3
queries = [[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]]
solution(rows, columns, queries)

In [ ]:
rows = 100
columns = 97
queries = [[1,1,100,97]]
solution(rows, columns, queries)

## 남 코드

In [47]:
def solution(rows, columns, queries):
    answer = []
    table = []
    for r in range(rows):
        table.append([a for a in range(r*columns+1, (r+1)*columns+1)])
    
    for query in queries:
        query = [x-1 for x in query] # 0부터 시작하는 인덱스에 맞춰 1씩 빼줌
        tmp = table[query[0]][query[1]] # 왼쪽 위 값 저장
        small = tmp
        
        # left
        for i in range(query[0]+1, query[2]+1):
            table[i-1][query[1]] = table[i][query[1]]
            small = min(small, table[i][query[1]])
        # bottom
        for i in range(query[1]+1, query[3]+1):
            table[query[2]][i-1] = table[query[2]][i]
            small = min(small, table[query[2]][i])
        # right
        for i in range(query[2]-1, query[0]-1, -1):
            table[i+1][query[3]] = table[i][query[3]]
            small = min(small, table[i][query[3]])
        # top
        for i in range(query[3]-1, query[1]-1, -1):
            table[query[0]][i+1] = table[query[0]][i]
            small = min(small, table[query[0]][i])
        table[query[0]][query[1]+1] = tmp
        
        answer.append(small)
    
    return answer

In [48]:
import sys


def solution(rows, columns, queries):
    arr = [[(i)*columns+(j+1) for j in range(columns)] for i in range(rows)]
    result = []
    for x1, y1, x2, y2 in queries:
        result.append(change(x1-1, y1-1, x2-1, y2-1, arr))
    return result


def change(x1, y1, x2, y2, arr):
    min_value = sys.maxsize
    # 맨 위의 맨 왼쪽 값을 기록
    temp = arr[x1][y1]
    # 왼쪽
    for k in range(x1, x2):
        arr[k][y1] = arr[k+1][y1]
        min_value = min(min_value, arr[k+1][y1])
    # 아래
    for k in range(y1, y2):
        arr[x2][k] = arr[x2][k+1]
        min_value = min(min_value, arr[x2][k+1])
    # 오른쪽
    for k in range(x2, x1, -1):
        arr[k][y2] = arr[k-1][y2]
        min_value = min(min_value, arr[k-1][y2])
    # 위
    for k in range(y2, y1+1, -1):
        arr[x1][k] = arr[x1][k-1]
        min_value = min(min_value, arr[x1][k-1])
    # 기록했던 값 업데이트
    arr[x1][y1+1] = temp
    min_value = min(min_value, temp)
    return min_value